// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (id, created_at, updated_at, white_id, black_id, time_control_base, time_control_increment, result, moves)
    VALUES ($1, NOW(), NOW(), $2, $3, $4, $5, $6, $7)
RETURNING
    id, created_at, updated_at, white_id, black_id, time_control_base, time_control_increment, result, moves
`

type CreateGameParams struct {
	ID                   uuid.UUID       `json:"id"`
	WhiteID              uuid.NullUUID   `json:"white_id"`
	BlackID              uuid.NullUUID   `json:"black_id"`
	TimeControlBase      int32           `json:"time_control_base"`
	TimeControlIncrement int32           `json:"time_control_increment"`
	Result               string          `json:"result"`
	Moves                json.RawMessage `json:"moves"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.ID,
		arg.WhiteID,
		arg.BlackID,
		arg.TimeControlBase,
		arg.TimeControlIncrement,
		arg.Result,
		arg.Moves,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteID,
		&i.BlackID,
		&i.TimeControlBase,
		&i.TimeControlIncrement,
		&i.Result,
		&i.Moves,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT
    g.id, g.created_at, g.updated_at, g.white_id, g.black_id, g.time_control_base, g.time_control_increment, g.result, g.moves,
    wu.name AS white_name,
    bu.name AS black_name
FROM
    games g
    LEFT JOIN users wu ON g.white_id = wu.id
    LEFT JOIN users bu ON g.black_id = bu.id
WHERE
    g.id = $1
`

type GetGameRow struct {
	ID                   uuid.UUID       `json:"id"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
	WhiteID              uuid.NullUUID   `json:"white_id"`
	BlackID              uuid.NullUUID   `json:"black_id"`
	TimeControlBase      int32           `json:"time_control_base"`
	TimeControlIncrement int32           `json:"time_control_increment"`
	Result               string          `json:"result"`
	Moves                json.RawMessage `json:"moves"`
	WhiteName            sql.NullString  `json:"white_name"`
	BlackName            sql.NullString  `json:"black_name"`
}

func (q *Queries) GetGame(ctx context.Context, id uuid.UUID) (GetGameRow, error) {
	row := q.db.QueryRowContext(ctx, getGame, id)
	var i GetGameRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WhiteID,
		&i.BlackID,
		&i.TimeControlBase,
		&i.TimeControlIncrement,
		&i.Result,
		&i.Moves,
		&i.WhiteName,
		&i.BlackName,
	)
	return i, err
}

const getGamesByUser = `-- name: GetGamesByUser :many
SELECT
    g.id,
    g.white_id,
    wu.name AS white_name,
    g.black_id,
    bu.name AS black_name,
    g.time_control_base,
    g.time_control_increment,
    g.result
FROM
    games g
    LEFT JOIN users wu ON g.white_id = wu.id
    LEFT JOIN users bu ON g.black_id = bu.id
WHERE
    g.white_id IS NOT DISTINCT FROM $1
    OR g.black_id IS NOT DISTINCT FROM $1
ORDER BY
    g.created_at DESC,
    g.id DESC
LIMIT $2 OFFSET ($3 - 1) * $2
`

type GetGamesByUserParams struct {
	WhiteID uuid.NullUUID `json:"white_id"`
	Limit   int32         `json:"limit"`
	Column3 interface{}   `json:"column_3"`
}

type GetGamesByUserRow struct {
	ID                   uuid.UUID      `json:"id"`
	WhiteID              uuid.NullUUID  `json:"white_id"`
	WhiteName            sql.NullString `json:"white_name"`
	BlackID              uuid.NullUUID  `json:"black_id"`
	BlackName            sql.NullString `json:"black_name"`
	TimeControlBase      int32          `json:"time_control_base"`
	TimeControlIncrement int32          `json:"time_control_increment"`
	Result               string         `json:"result"`
}

func (q *Queries) GetGamesByUser(ctx context.Context, arg GetGamesByUserParams) ([]GetGamesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getGamesByUser, arg.WhiteID, arg.Limit, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGamesByUserRow
	for rows.Next() {
		var i GetGamesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.WhiteID,
			&i.WhiteName,
			&i.BlackID,
			&i.BlackName,
			&i.TimeControlBase,
			&i.TimeControlIncrement,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamesCount = `-- name: GetGamesCount :one
SELECT
    COUNT(*)
FROM
    games
WHERE
    white_id IS NOT DISTINCT FROM $1
    OR black_id IS NOT DISTINCT FROM $1
`

func (q *Queries) GetGamesCount(ctx context.Context, whiteID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGamesCount, whiteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
