// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lichess_accounts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLichessAccount = `-- name: GetLichessAccount :one
SELECT
    user_id, id, username, encrypted_token, linked_at, expires_at
FROM
    lichess_accounts
WHERE
    user_id = $1
`

func (q *Queries) GetLichessAccount(ctx context.Context, userID uuid.UUID) (LichessAccount, error) {
	row := q.db.QueryRowContext(ctx, getLichessAccount, userID)
	var i LichessAccount
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Username,
		&i.EncryptedToken,
		&i.LinkedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const linkLichessAccount = `-- name: LinkLichessAccount :one
INSERT INTO lichess_accounts (user_id, id, username, encrypted_token, linked_at, expires_at)
    VALUES ($1, $2, $3, $4, NOW(), $5)
RETURNING
    user_id, id, username, encrypted_token, linked_at, expires_at
`

type LinkLichessAccountParams struct {
	UserID         uuid.UUID `json:"user_id"`
	ID             string    `json:"id"`
	Username       string    `json:"username"`
	EncryptedToken []byte    `json:"encrypted_token"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) LinkLichessAccount(ctx context.Context, arg LinkLichessAccountParams) (LichessAccount, error) {
	row := q.db.QueryRowContext(ctx, linkLichessAccount,
		arg.UserID,
		arg.ID,
		arg.Username,
		arg.EncryptedToken,
		arg.ExpiresAt,
	)
	var i LichessAccount
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.Username,
		&i.EncryptedToken,
		&i.LinkedAt,
		&i.ExpiresAt,
	)
	return i, err
}
