// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Game struct {
	ID                   uuid.UUID       `json:"id"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
	WhiteID              uuid.NullUUID   `json:"white_id"`
	BlackID              uuid.NullUUID   `json:"black_id"`
	TimeControlBase      int32           `json:"time_control_base"`
	TimeControlIncrement int32           `json:"time_control_increment"`
	Result               string          `json:"result"`
	Moves                json.RawMessage `json:"moves"`
}

type LichessAccount struct {
	UserID         uuid.UUID `json:"user_id"`
	LinkedAt       time.Time `json:"linked_at"`
	ID             string    `json:"id"`
	Username       string    `json:"username"`
	EncryptedToken []byte    `json:"encrypted_token"`
}

type RefreshToken struct {
	Token     string       `json:"token"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	UserID    uuid.UUID    `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Email          string    `json:"email"`
	Name           string    `json:"name"`
	HashedPassword string    `json:"hashed_password"`
}
